[tasks.build]
description = "Build the release-version rvgen"
dir = "."
run = "cargo build --release"
sources = [
    "Cargo.toml",
    "Cargo.lock",
    "src/**/*.rs",
]
outputs = ["./rvgen"]

[tasks.test-smc]
description = "Generate 30000 self-modifying programs and check that each passes on Spike"
run = "cargo test --release smc_programs_pass_on_spike -- --ignored"

[tasks.disassemble]
run = [
    "riscv64-unknown-elf-objdump --disassemble",
]

[tasks.analyze]
run = [
    "python3 scripts/analyze_elf.py",
]

[tasks.count]
description = "Count the number of execcuted instructions"
run = [
    "which python3",
    "python3 scripts/count_spike_instructions.py elfs/ --output out/stats.toml --plot out/stats.png",
]

[tasks.snapshot]
description = "Snapshot current working tree and upload to Github"
run = "./scripts/snapshot.sh"

[tasks.clean]
description = "Clean the build files"
run = [
    "cargo clean",
    "rm -f rvprog.elf",
    "rm -rf elfs",
    "rm -rf out",
]
