[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rvgen"
version = "0.1.0"
description = "A standalone RISC-V instruction and test program generator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyelftools>=0.30",
    "numpy>=1.20.0",
    "z3-solver>=4.12.0",
]

[project.scripts]
rvgen = "rvgen.cli:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "termcolor",
    "tqdm",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["rvgen*"]

[tool.setuptools.package-data]
"rvgen" = [
    "templates/*",
]