# Copyright 2026 Flavien Solt, Quentin Bordier ETH Zurich.
# Licensed under the General Public License, Version 3.0, see LICENSE for details.
# SPDX-License-Identifier: GPL-3.0-only


from enum import Enum, auto

from instgen import (
    IntLoadInstr,
    IntStoreInstr,
    FloatLoadInstr,
    FloatStoreInstr,
    AmoInstr,
    AmoStore,
)


class RegType(Enum):
    Data = auto()
    Address = auto()
    Standard = auto()
    Csr = auto()
    Frm = auto()


# These are fields of the Floating-Point Control and Status Register (fcsr)
class AccCsr(Enum):
    # Accumulating CSR
    NV = auto()
    OF = auto()
    UF = auto()
    NX = auto()
    DZ = auto()

LOAD_INSTR = (IntLoadInstr, FloatLoadInstr)
STORE_INSTR = (IntStoreInstr, FloatStoreInstr)
AMO_INSTR = (AmoInstr, AmoStore)
MEMOP = (
    IntLoadInstr,
    FloatLoadInstr,
    IntStoreInstr,
    FloatStoreInstr,
    AmoInstr,
    AmoStore,
)

# FPU instructions which might have frm as a source reg
FRM_FLOAT = (
    "fmadd.s",
    "fmsub.s",
    "fnmsub.s",
    "fnmadd.s",
    "fmadd.d",
    "fmsub.d",
    "fnmsub.d",
    "fnmadd.d",
    "fadd.s",
    "fsub.s",
    "fmul.s",
    "fdiv.s",
    "fadd.d",
    "fsub.d",
    "fmul.d",
    "fdiv.d",
    "fsqrt.s",
    "fsqrt.d",
    "fcvt.s.d",
    "fcvt.w.s",
    "fcvt.wu.s",
    "fcvt.l.s",
    "fcvt.lu.s",
    "fcvt.w.d",
    "fcvt.wu.d",
    "fcvt.l.d",
    "fcvt.lu.d",
    "fcvt.s.w",
    "fcvt.s.wu",
    "fcvt.s.l",
    "fcvt.s.lu",
    "fcvt.d.l",
    "fcvt.d.lu",
)

SYNTACTIC_DEP_PROPAGUATION = {
    # .RV32I Base Integer Instruction Set
    "lui": (None, [RegType.Standard], None, False, False),
    "auipc": (None, [RegType.Standard], None, False, False),
    "jal": (None, [RegType.Standard], None, False, False),
    "jalr": ([RegType.Standard], [RegType.Standard], None, False, False),
    "beq": ([RegType.Standard, RegType.Standard], None, None, False, False),
    "bne": ([RegType.Standard, RegType.Standard], None, None, False, False),
    "blt": ([RegType.Standard, RegType.Standard], None, None, False, False),
    "bge": ([RegType.Standard, RegType.Standard], None, None, False, False),
    "bltu": ([RegType.Standard, RegType.Standard], None, None, False, False),
    "bgeu": ([RegType.Standard, RegType.Standard], None, None, False, False),
    "lb": ([RegType.Address], [RegType.Standard], None, False, False),
    "lh": ([RegType.Address], [RegType.Standard], None, False, False),
    "lw": ([RegType.Address], [RegType.Standard], None, False, False),
    "lbu": ([RegType.Address], [RegType.Standard], None, False, False),
    "lhu": ([RegType.Address], [RegType.Standard], None, False, False),
    "sb": ([RegType.Address, RegType.Data], None, None, False, False),
    "sh": ([RegType.Address, RegType.Data], None, None, False, False),
    "sw": ([RegType.Address, RegType.Data], None, None, False, False),
    "addi": ([RegType.Standard], [RegType.Standard], None, False, True),
    "slti": ([RegType.Standard], [RegType.Standard], None, False, True),
    "sltiu": ([RegType.Standard], [RegType.Standard], None, False, True),
    "xori": ([RegType.Standard], [RegType.Standard], None, False, True),
    "ori": ([RegType.Standard], [RegType.Standard], None, False, True),
    "andi": ([RegType.Standard], [RegType.Standard], None, False, True),
    "slli": ([RegType.Standard], [RegType.Standard], None, False, True),
    "srli": ([RegType.Standard], [RegType.Standard], None, False, True),
    "srai": ([RegType.Standard], [RegType.Standard], None, False, True),
    "add": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "sub": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "sll": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "slt": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "sltu": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "xor": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "srl": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "sra": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "or": ([RegType.Standard, RegType.Standard], [RegType.Standard], None, False, True),
    "and": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "fence": (None, None, None, False, False),
    "fence.i": (None, None, None, False, False),
    "ecall": (None, None, None, False, False),
    "ebreak": (None, None, None, False, False),
    "csrrw": (
        [RegType.Standard, RegType.Csr],
        [RegType.Standard, RegType.Csr],
        None,
        True,
        True,
    ),  # CONDITIONAL and special condition
    "csrrs": (
        [RegType.Standard, RegType.Csr],
        [RegType.Standard, RegType.Csr],
        None,
        True,
        True,
    ),  # CONDITIONAL and special condition
    "csrrc": (
        [RegType.Standard, RegType.Csr],
        [RegType.Standard, RegType.Csr],
        None,
        True,
        True,
    ),  # CONDITIONAL and special condition
    "csrrwi": ([RegType.Csr], [RegType.Standard, RegType.Csr], None, True, True),
    "csrrsi": ([RegType.Csr], [RegType.Standard, RegType.Csr], None, True, True),
    "csrrci": ([RegType.Csr], [RegType.Standard, RegType.Csr], None, True, True),
    # .RV64I Base Integer Instruction Set
    "lwu": ([RegType.Address], [RegType.Standard], None, False, False),
    "ld": ([RegType.Address], [RegType.Standard], None, False, False),
    "sd": ([RegType.Address, RegType.Data], None, None, False, False),
    "slli": ([RegType.Standard], [RegType.Standard], None, False, True),
    "srli": ([RegType.Standard], [RegType.Standard], None, False, True),
    "srai": ([RegType.Standard], [RegType.Standard], None, False, True),
    "addiw": ([RegType.Standard], [RegType.Standard], None, False, True),
    "slliw": ([RegType.Standard], [RegType.Standard], None, False, True),
    "srliw": ([RegType.Standard], [RegType.Standard], None, False, True),
    "sraiw": ([RegType.Standard], [RegType.Standard], None, False, True),
    "addw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "subw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "sllw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "srlw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "sraw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    # .RV32M Standard Extension
    "mul": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "mulh": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "mulhsu": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "mulhu": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "div": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "divu": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "rem": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "remu": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    # .RV64M Standard Extension
    "mulw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "divw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "divuw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "remw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "remuw": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    # .RV32A Standard Extension
    "lr.w": ([RegType.Address], [RegType.Standard], None, False, False),
    "sc.w": ([RegType.Address, RegType.Data], [RegType.Standard], None, True, False),
    "amoswap.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoadd.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoxor.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoand.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoor.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amomin.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amomax.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amominu.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amomaxu.w": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    # .RV64A Standard Extension
    "lr.d": ([RegType.Address], [RegType.Standard], None, False, False),
    "sc.d": ([RegType.Address, RegType.Data], [RegType.Standard], None, True, False),
    "amoswap.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoadd.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoxor.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoand.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amoor.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amomin.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amomax.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amominu.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    "amomaxu.d": (
        [RegType.Address, RegType.Data],
        [RegType.Standard],
        None,
        False,
        False,
    ),
    # .RV32F Standard Extension
    "flw": ([RegType.Address], [RegType.Standard], None, False, False),
    "fsw": ([RegType.Address, RegType.Data], None, None, False, False),
    "fmadd.s": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fmsub.s": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fnmsub.s": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fnmadd.s": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fadd.s": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.NX],
        True,
        True,
    ),
    "fsub.s": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.NX],
        True,
        True,
    ),
    "fmul.s": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fdiv.s": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.DZ, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fsqrt.s": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fsgnj.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "fsgnjn.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "fsgnjx.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "fmin.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fmax.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fcvt.w.s": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fcvt.wu.s": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fmv.x.w": ([RegType.Standard], [RegType.Standard], None, False, True),
    "feq.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "flt.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fle.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fclass.s": ([RegType.Standard], [RegType.Standard], None, False, True),
    "fcvt.s.w": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NX],
        True,
        True,
    ),
    "fcvt.s.wu": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NX],
        True,
        True,
    ),
    "fmv.w.x": ([RegType.Standard], [RegType.Standard], None, False, True),
    # .RV64F Standard Extension
    "fcvt.l.s": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fcvt.lu.s": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fcvt.s.l": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NX],
        True,
        True,
    ),
    "fcvt.s.lu": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NX],
        True,
        True,
    ),
    # .RV32D Standard Extension
    "fld": ([RegType.Address], [RegType.Standard], None, False, False),
    "fsd": ([RegType.Address, RegType.Data], None, None, False, False),
    "fmadd.d": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fmsub.d": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fnmsub.d": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fnmadd.d": (
        [RegType.Standard, RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fadd.d": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.NX],
        True,
        True,
    ),
    "fsub.d": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.NX],
        True,
        True,
    ),
    "fmul.d": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fdiv.d": (
        [RegType.Standard, RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.DZ, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fsqrt.d": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fsgnj.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "fsgnjn.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "fsgnjx.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        None,
        False,
        True,
    ),
    "fmin.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fmax.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fcvt.s.d": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.OF, AccCsr.UF, AccCsr.NX],
        True,
        True,
    ),
    "fcvt.d.s": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "feq.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "flt.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fle.d": (
        [RegType.Standard, RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV],
        False,
        True,
    ),
    "fclass.d": ([RegType.Standard], [RegType.Standard], None, False, True),
    "fcvt.w.d": (
        [RegType.Standard],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fcvt.wu.d": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fcvt.d.w": ([RegType.Standard], [RegType.Standard], None, False, True),
    "fcvt.d.wu": ([RegType.Standard], [RegType.Standard], None, False, True),
    # .RV64D Standard Extension
    "fcvt.l.d": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fcvt.lu.d": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NV, AccCsr.NX],
        True,
        True,
    ),
    "fmv.x.d": ([RegType.Standard], [RegType.Standard], None, False, True),
    "fcvt.d.l": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NX],
        True,
        True,
    ),
    "fcvt.d.lu": (
        [RegType.Standard, RegType.Frm],
        [RegType.Standard],
        [AccCsr.NX],
        True,
        True,
    ),
    "fmv.d.x": ([RegType.Standard], [RegType.Standard], None, False, True),
}
