# Copyright 2026 Flavien Solt, Quentin Bordier ETH Zurich.
# Licensed under the General Public License, Version 3.0, see LICENSE for details.
# SPDX-License-Identifier: GPL-3.0-only


from typing import TYPE_CHECKING
from mcm.types import HartId, InstrCoord
from riscv.rvwmo import (
    MEMOP,
    SYNTACTIC_DEP_PROPAGUATION,
)
from mcm.memops import MemFence, MemInstr, Store, Load, Amo
from riscv import FenceOrdering, Ordering, CSR, IntReg
from instgen import (
    WrapperInstr,
    RVInstr,
    IntStoreInstr,
    FloatStoreInstr,
    BranchInstr,
    JALRInstr,
    AmoInstr,
    IntLoadInstr,
    IntStoreInstr,
)

if TYPE_CHECKING:
    from states.corestate import CoreState
    from riscv import FloatReg


class PpoRules:
    """class responsible for the computation of the different PPO rules
    relationships
    """

    def __init__(
        self,
        step_memops: dict[HartId, dict[InstrCoord, MemInstr]],
        step_fences: dict[HartId, dict[InstrCoord, MemFence]],
    ):
        # FIXME for the time being, wrapped instruction play no role, becuase
        # they have no will not used shared addresses, they can be safely
        # ignored. They also create no deps, etc. But in the future, they might
        # and we have to fix this
        self.step_memops: dict[HartId, dict[InstrCoord, MemInstr]] = step_memops
        self.step_fences = step_fences

    def gather_all_ppo_constraints(
        self,
        corestates: dict[HartId, "CoreState"],
        only_syntactic_deps: bool,
        collect_guarded_edges: bool = False
    ):
        """Gather all of the PPO constarints. Modifies the constraints list
        of the memory operations in place
        """

        for hartid, corestate in corestates.items():
            if not only_syntactic_deps:
                # Overlapping addresses
                self._ppo_rule_1(hartid)
                self._ppo_rule_2(hartid)
                self._ppo_rule_3()  # pass, guarded edges

                # Explicut synchronization
                self._ppo_rule_4(hartid)
                self._ppo_rule_5(hartid)
                self._ppo_rule_6(hartid)
                self._ppo_rule_7(hartid)
                self._ppo_rule_8()  # pass, guarded edges

            # Syntactic dependencies
            self._ppo_rule_9_10_11(hartid, corestate)

            if not only_syntactic_deps:
                # Pipeline dependencies
                self._ppo_rule_12(hartid)  # pass, guarded edges
                self._ppo_rule_13(hartid)

    def _ppo_rule_1(self, hartid: HartId):
        """This function computes the rule 1 realtions, memop a precedes b:

        b is a store, and a and b access overlapping memory addresses

        If A and B access the same address (or have any overlapping footprint),
        then A must appear before B in global memory order:
        - A load A must determine its value before B becomes globally visible
        - A store A must become globally visible before B becomes globally
        visible
        """
        # Build a list of all stores
        store_ops: list[MemInstr] = []
        for memop in self.step_memops[hartid].values():
            if isinstance(memop, (Store, Amo)):
                store_ops.append(memop)

        # For each memory operations, find all later stores that overlap in
        # address
        for instr_a in self.step_memops[hartid].values():
            for instr_b in store_ops:
                if instr_b.idx <= instr_a.idx:
                    continue  # Only consider later stores
                # Check for address overlap
                if instr_a._check_overlap(instr_b):
                    instr_a.rw_w_overlap.add(instr_b.idx)

    def _ppo_rule_2(self, hartid: HartId):
        """This function computes the rule 2 relations, memop a precedes b:

        a and b are loads, x is a byte read by both a and b, there is no store
        to x between a and b in program order, and a and b return values for x
        written by different memory operations, or inforamlly:

        We can, for our prediction, always assume PPO, as the extra edge will
        not change the value that can be loaded ? We want to avoid computing a
        scenario where a load returns a value that is stale

        Since the program will explore all possible combinations of load return
        values, I can conservatively apply PPO Rule 2 to all overlapping loads
        in program order — even if they might return the same value — because
        the constraint will only matter in cases where the values differ.
        """
        pass

    def _ppo_rule_3(self):
        """This function computes the rule 3 relations, memop a precedes b:

        a is generated by an AMO or SC instruction, b is a load, and b returns a
        value written by a, informally:

        A load B cannot determine its return value by forwarding from an Atomic
        Memory Operation or Store-Conditional operation that has not yet become
        globally visible

        THIS IS A GUARDED EDGE -> restrict store buffer effect when
        computing the store/laod pairs:
         if the store of a load-store pair is an AMO, and the AMO comes from the
         same hart as the load, then the global ordering where the AMO is after
         the load in the GMO is not valid
        """
        pass

    # Explicit Synchronisation rules

    def _ppo_rule_4(self, hartid: HartId):
        """This function computes the rule 4 relations, memop a precedes b:

        Orders operations in the predecessor set before operations in the
        successor set
        """
        LOADS = {"lb", "lh", "lw", "lbu", "lhu", "lwu", "ld", "flw", "fld"}
        STORES = {"sb", "sh", "sw", "sd", "fsw", "fsd"}
        AMOS = {
            "amoswap.w",
            "amoadd.w",
            "amoxor.w",
            "amoand.w",
            "amoor.w",
            "amomin.w",
            "amomax.w",
            "amominu.w",
            "amomaxu.w",
            "amoswap.d",
            "amoadd.d",
            "amoxor.d",
            "amoand.d",
            "amoor.d",
            "amomin.d",
            "amomax.d",
            "amominu.d",
            "amomaxu.d",
        }
        MEMOPS = AMOS | STORES | LOADS

        def get_pred_succ_ops(fence_ordering):
            """Return (pred_ops, succ_ops) based on fence ordering."""
            match fence_ordering:
                case FenceOrdering.W_W:
                    predecessor_set = STORES | AMOS
                    successor_set = STORES | AMOS
                    return [(predecessor_set, successor_set)]
                case FenceOrdering.R_R:
                    predecessor_set = LOADS | AMOS
                    successor_set = LOADS | AMOS
                    return [(predecessor_set, successor_set)]
                case FenceOrdering.RW_RW:
                    predecessor_set = MEMOPS
                    successor_set = MEMOPS
                    return [(predecessor_set, successor_set)]
                case FenceOrdering.RW_W:
                    predecessor_set = MEMOPS
                    successor_set = STORES | AMOS
                    return [(predecessor_set, successor_set)]
                case FenceOrdering.R_RW:
                    predecessor_set = LOADS | AMOS
                    successor_set = MEMOPS
                    return [(predecessor_set, successor_set)]
                case FenceOrdering.TSO:
                    predecessor_set_0 = LOADS | AMOS
                    successor_set_0 = MEMOPS
                    predecessor_set_1 = STORES | AMOS
                    successor_set_1 = STORES | AMOS
                    return [
                        (predecessor_set_0, successor_set_0),
                        (predecessor_set_1, successor_set_1),
                    ]
                case _:
                    raise ValueError("Unknown fence ordering")

        # Build once: list and idx->memop map (avoid indexing into dict.values())
        memops_list = list(self.step_memops[hartid].values())
        idx_to_memop = {m.idx: m for m in memops_list}
        for fence in self.step_fences[hartid].values():
            # Get the predecessor and successor sets
            fence_ordering_sets = get_pred_succ_ops(fence.fence_ordering)

            # Handle multiple pred/succ sets (e.g., TSO case)
            for pred_ops, succ_ops in fence_ordering_sets:
                for instr in memops_list:
                    if fence.prev_memop_idx >= instr.idx:
                        if instr.instr_str in pred_ops:
                            fence.predecessor_set.append(instr.idx)
                    else:
                        if instr.instr_str in succ_ops:
                            fence.successor_set.append(instr.idx)

            # Update fence brackets immediately after building sets
            for predecessor in fence.predecessor_set:
                for successor in fence.successor_set:
                    # Use map instead of indexing list by idx
                    idx_to_memop[predecessor].fence_successor.add(successor)

    def _ppo_rule_5(self, hartid: HartId):
        """This function computes the rule 5 relations, memop a precedes b:

        a has an acquire annotation
        """
        # Iterate once over memops; use each memop's own idx to find later ops
        memops = list(self.step_memops[hartid].values())
        for instr_a in memops:
            if isinstance(instr_a, Amo) and instr_a.ordering in (
                Ordering.Acq,
                Ordering.Seq,
            ):
                for instr_b in memops:
                    if instr_b.idx <= instr_a.idx:
                        continue
                    instr_a.acquire.add(instr_b.idx)

    def _ppo_rule_6(self, hartid: HartId):
        """This function computes the rule 6 relations, memop a precedes b:

        b has a release annotation
        """
        # Iterate once over memops; use each memop's own idx to find earlier ops
        memops = list(self.step_memops[hartid].values())
        for instr_b in memops:
            if isinstance(instr_b, Amo) and instr_b.ordering in (
                Ordering.Rel,
                Ordering.Seq,
            ):
                for instr_a in memops:
                    if instr_a.idx < instr_b.idx:
                        instr_a.release.add(instr_b.idx)

    def _ppo_rule_7(self, hartid: HartId):
        """This function computes the rule 7 relations, memop a precedes b:

        a and b both have RCsc annotations

        There is currently no RCpc annotation (except for Ztso, is some special
        case) supported by the RISCV ISA
        """
        # Iterate once over memops; use idx comparisons for ordering
        memops = list(self.step_memops[hartid].values())
        for instr_a in memops:
            if isinstance(instr_a, Amo) and instr_a.ordering in (
                Ordering.Acq,
                Ordering.Rel,
                Ordering.Seq,
            ):
                for instr_b in memops:
                    if instr_b.idx <= instr_a.idx:
                        continue
                    if isinstance(instr_b, Amo) and instr_b.ordering in (
                        Ordering.Acq,
                        Ordering.Rel,
                        Ordering.Seq,
                    ):
                        instr_a.sequential.add(instr_b.idx)

    def _ppo_rule_8(self):
        """This function computes the rule 8 relations, memop a precedes b:

        a is paired with b
        """
        pass

    def _ppo_rule_9_10_11(self, hartid: HartId, corestate: "CoreState"):
        """Computes PPO rules 9, 10 & 11 for syntactic dependencies.

        These rules state that memory operation 'a' precedes 'b' when:
        - Rule 9: b is a store with syntactic control dependency on a
        - Rule 10: b has a syntactic address dependency on a
        - Rule 11: b is a store with syntactic data dependency on a

        The algorithm tracks dependency chains by following register dependencies
        from the initial memory operation through subsequent instructions.
        """
        for memop in self.step_memops[hartid].values():
            if isinstance(memop, Store):
                continue  # Stores do not generate dependencies
            analyzer = SyntacticDependencyAnalyzer(memop, self.step_memops[hartid])
            analyzer.analyze_dependencies(corestate)

    def _ppo_rule_12(self, hartid: HartId):
        """This function computes the rule 12 relations, memop a precedes b:

        b is a load, and there exists some store m between a and b in program
        order such that m has an address or data dependency on a, and b returns
        a value written by m

        B returns a value from an earlier store M (address overlap) in the same
        hart, and M has an address or data dependency on A
        """
        pass

    def _ppo_rule_13(self, hartid: HartId):
        """This function computes the rule 13 relations, memop a precedes b:

        b is a store, and there exists some instruction m between a and b in
        program order such that m has an address dependency on a

        B follows M in program order, and M has an address dependency on A
        """

        def add_all_later_stores(first_dep):
            """finds and append all stores after a given index"""
            for instr_b in self.step_memops[hartid].values():
                if instr_b.idx > first_dep and isinstance(instr_b, (Store, Amo)):
                    instr_a.rule_13.add(instr_b.idx)

        for instr_a in self.step_memops[hartid].values():
            if instr_a.syntactic_addr_dep != set():
                # find the first instr m (must be a store, since it is a dep)
                # with an address dependency to a
                first_po_dep = min(instr_a.syntactic_addr_dep)
                add_all_later_stores(first_po_dep)


class SyntacticDependencyAnalyzer:
    """Helper class for analyzing syntactic dependencies for a single memory operation.

    This class encapsulates the complex logic for tracking register dependencies
    from a specific memory operation through subsequent instruction sequences to
    determine control, address, and data dependencies.
    """

    def __init__(self, base_memop: MemInstr, hart_memops: dict[InstrCoord, MemInstr]):
        self.base_memop = base_memop
        self.hart_memops = hart_memops
        # Initialize analysis state immediately
        self.dependency_carriers: "set[IntReg | FloatReg | CSR]" = set()
        self.last_memop_coord = base_memop.instr_coord
        self.ctrl_dep_search_active = True
        self._analysis_completed = False  # Prevent multiple calls

    def analyze_dependencies(self, corestate: "CoreState"):
        """Analyze syntactic dependencies for the source memory operation."""
        if self._analysis_completed:
            raise RuntimeError(
                "analyze_dependencies can only be called once per instance"
            )

        # Initialize dependency carriers from the instruction's output registers
        bb_idx, instr_idx = self.base_memop.instr_coord
        instr = corestate.basic_blocks[bb_idx][instr_idx]
        self.dependency_carriers = set(instr.get_outputregs())
        assert self.dependency_carriers

        if self.dependency_carriers == {IntReg.zero}:
            self._analysis_completed = True
            return  # Zero register does not carry dependencies

        # Scan through subsequent instructions
        self._scan_for_dependencies(corestate)
        self._analysis_completed = True

    def _scan_for_dependencies(self, corestate: "CoreState"):
        """Scan through instructions to find all types of dependencies."""
        start_bb_idx, start_instr_idx = self.base_memop.instr_coord
        for bb_idx in range(start_bb_idx, len(corestate.basic_blocks)):
            current_bb = corestate.basic_blocks[bb_idx]
            start_idx = start_instr_idx + 1 if bb_idx == start_bb_idx else 0

            for instr_idx in range(start_idx, len(current_bb)):
                current_instr = current_bb[instr_idx]
                instr_coord = (bb_idx, instr_idx)
                if instr_coord in corestate.mcm_reset_locs:
                    return  # reached the end of the solving step
                # Update last memory operation seen
                is_memop = isinstance(current_instr, MEMOP)
                is_not_interrupt = (
                    isinstance(current_instr, (IntLoadInstr, IntStoreInstr))
                    and not current_instr.is_interrupt
                )
                if is_memop and is_not_interrupt:
                    self.last_memop_coord = instr_coord
                self._analyze_instruction_dependencies(current_instr, instr_coord)
                self.dependency_carriers = self._update_dependency_carriers(
                    current_instr
                )
                if not self.dependency_carriers or self.dependency_carriers == {
                    IntReg.zero
                }:
                    return

    def _analyze_instruction_dependencies(
        self, current_instr: RVInstr, instr_coord: InstrCoord
    ):
        """Analyze the current instruction for all types of dependencies."""
        # Control dependencies (only check while still active)
        if self.ctrl_dep_search_active:
            if self._handle_control_dependency(current_instr):
                self.ctrl_dep_search_active = False
        # Address and data dependencies
        self._handle_address_dependency(current_instr, instr_coord)
        self._handle_data_dependency(current_instr, instr_coord)

    def _handle_control_dependency(self, current_instr: RVInstr) -> bool:
        """Check for control dependencies from branch or jump instructions."""
        is_dependent_branch = isinstance(current_instr, BranchInstr) and (
            current_instr.rs1 in self.dependency_carriers
            or current_instr.rs2 in self.dependency_carriers
        )
        is_dependent_jalr = (
            isinstance(current_instr, JALRInstr)
            and current_instr.rs1 in self.dependency_carriers
        )
        if is_dependent_branch or is_dependent_jalr:
            # add the dependency to all store after the CFI
            last_memop_idx = self.hart_memops[self.last_memop_coord].idx
            for memop in self.hart_memops.values():
                if memop.idx <= last_memop_idx:
                    continue
                if isinstance(memop, (Store, Amo)):
                    self.base_memop.syntactic_ctrl_dep.add(memop.idx)
            return True
        return False

    def _handle_address_dependency(self, current_instr: RVInstr, instr_coord: tuple):
        """Check for address dependencies in memory operations."""
        if (
            isinstance(current_instr, MEMOP)
            and current_instr.rs1 in self.dependency_carriers
        ):
            target_memop_idx = self.hart_memops[instr_coord].idx
            self.base_memop.syntactic_addr_dep.add(target_memop_idx)

    def _handle_data_dependency(self, current_instr: RVInstr, instr_coord: tuple):
        """Check for data dependencies in store operations."""
        target_memop_idx = None

        if (
            isinstance(current_instr, IntStoreInstr)
            and current_instr.rs2 in self.dependency_carriers
            and not current_instr.is_interrupt
        ):
            target_memop_idx = self.hart_memops[instr_coord].idx
        elif (
            isinstance(current_instr, FloatStoreInstr)
            and current_instr.frs2 in self.dependency_carriers
        ):
            target_memop_idx = self.hart_memops[instr_coord].idx
        elif (
            isinstance(current_instr, AmoInstr)
            and current_instr.rs2 in self.dependency_carriers
        ):
            target_memop_idx = self.hart_memops[instr_coord].idx

        if target_memop_idx is not None:
            self.base_memop.syntactic_data_dep.add(target_memop_idx)

    def _update_dependency_carriers(
        self, current_instr: RVInstr
    ) -> "set[IntReg | FloatReg | CSR]":
        """Update the set of dependency carriers based on the current instruction.

        Rules:
        1. If a carrier register is overwritten (output but not input), remove it
        2. If a carrier register is used as input and the instruction propagates
           dependencies, add the output registers as new carriers
        """
        source_regs = current_instr.get_inputregs()
        dest_regs = current_instr.get_outputregs()
        new_carriers = set()
        carriers_to_remove = set()

        for carrier_reg in self.dependency_carriers:
            # carrier used as input, check if dependency propagates
            if carrier_reg in source_regs:
                propagated_regs = self._is_propaguating(current_instr)
                if propagated_regs:
                    new_carriers.update(propagated_regs)
            # carrier is overwritten (used as output)
            if carrier_reg in dest_regs:
                carriers_to_remove.add(carrier_reg)

        updated_carriers = self.dependency_carriers - carriers_to_remove
        updated_carriers.update(new_carriers)
        return updated_carriers

    def _is_propaguating(self, instr: "RVInstr") -> "list[IntReg | FloatReg | CSR]":
        """Returns the set of registers to which a dependency has been carried.
        Wrapped instructions are first unwrapped. Then, we return an empty list if
        no dependendency is carried.

        We assume that at least one of the source register is a carrier
        """
        if isinstance(instr, WrapperInstr):
            instr = instr.wrapped_instr
        instr_carry = SYNTACTIC_DEP_PROPAGUATION.get(instr.instr_str)
        assert instr_carry is not None
        carries_dependency = instr_carry[4]
        accumulating_csrs = instr_carry[2]
        if not carries_dependency:
            return []
        if accumulating_csrs is None:
            return instr.get_outputregs()
        else:
            # accumulating regs, since they propaguate to/from themselves, we do not
            # need fine grained tracking. Also, because the only other way
            return instr.get_outputregs() + [CSR.FFLAGS, CSR.FCSR]
