# Copyright 2026 Flavien Solt, Quentin Bordier ETH Zurich.
# Licensed under the General Public License, Version 3.0, see LICENSE for details.
# SPDX-License-Identifier: GPL-3.0-only


# This module generates ELF files from ..a program generated by Cascade.

from elftools.elf.elffile import ELFFile
import os
import subprocess
from typing import TYPE_CHECKING
import runparams
from params import (
    TOHOST_ADDR,
    MCM_RESET_HANDLER_LEN,
    DATA_SECTION_BASE,
    STRESS_SECTION_BASE,
)
from riscv import ILEN, DWORD_SIZE

if TYPE_CHECKING:
    from proggen import TestCaseGenerator
    from params import TestParams


def gen_elf(
    inbytes_text: bytes,
    inbytes_stress: bytes,
    destination_path: str,
    is_rv64: bool,
    design_name: str,
    is_rtl: bool,
) -> None:
    """
    Genrates an elf file from ..a program in bytes, given an byte stream for the
    .text section of the ELF file. For each elf file, we first make a template
    with a .text section of the desired size. Then the .text section is replaced
    with the given byte stream.
    """

    inbytes_text_len = len(inbytes_text)
    if inbytes_text_len % 4 != 0:
        inbytes_text_len += 4 - (inbytes_text_len % 4)
        inbytes_text = inbytes_text.ljust(inbytes_text_len, b"\x00")

    if is_rv64:
        MARCH = "rv64g"
        MABI = "lp64"
    else:
        MARCH = "rv32g"
        MABI = "ilp32"

    # TODO design boot addr should be passed as an argument to the linker
    script_dir = os.path.dirname(os.path.realpath(__file__))
    if not runparams.DEBUG_RTL and is_rtl and design_name in ("naxriscv", "vexiiriscv"):
        template_dir = os.path.join(script_dir, "elf_template_naxriscv")
    else:
        template_dir = os.path.join(script_dir, "elf_template")

    CC = "riscv64-unknown-elf-gcc"
    RV_ARCH_FLAGS = f"-march={MARCH} -mabi={MABI}"
    RISCV_GCC_OPTS = (
        f"{RV_ARCH_FLAGS} "
        "-mcmodel=medany "
        "-static "
        "-std=gnu99 "
        "-O0 "
        "-fno-common "
        "-fno-builtin-printf "
    )
    LDFLAGS = (
        f"-T{template_dir}/link.ld "
        "-static "
        "-nostdlib "
        "-nostartfiles "
        f"-Wl,--defsym TOHOST_ADDR={TOHOST_ADDR} "
        f"-Wl,--defsym DATA_SECTION_BASE={DATA_SECTION_BASE} "
        f"-Wl,--defsym STRESS_SECTION_BASE={STRESS_SECTION_BASE}"
    )
    stress_flag = (
        " -DSTRESS_CORE_ENABLE" if getattr(runparams, "FUZZ_STRESS_CORE", False) else ""
    )
    command = (
        f"{CC} "
        f"{RISCV_GCC_OPTS} "
        f"-DTEXT_LEN={inbytes_text_len}{stress_flag} "
        f"{template_dir}/main.S "
        f"-o {destination_path} "
        f"{LDFLAGS}"
    )
    subprocess.run(command, shell=True, check=True)

    with open(destination_path, "rb") as elf_template:
        elf_template_b = elf_template.read()
        elf_file = ELFFile(elf_template)
        text_section = None
        for sec in elf_file.iter_sections():
            if sec.name == ".text":
                text_section = sec
            if sec.name == ".stress_core":
                stress_section = sec
        if text_section is None:
            raise ValueError("Could not find the .text section")
        text_sh_off = text_section["sh_offset"]
        text_sh_size = text_section["sh_size"]
        assert len(inbytes_text) == text_sh_size
        new_elf = (
            elf_template_b[:text_sh_off]
            + inbytes_text
            + elf_template_b[text_sh_off + text_sh_size :]
        )

        if runparams.FUZZ_STRESS_CORE:
            stress_sh_off = stress_section["sh_offset"]
            stress_sh_size = stress_section["sh_size"]
            new_elf = (
                new_elf[:stress_sh_off]
                + inbytes_stress
                + new_elf[stress_sh_off + stress_sh_size :]
            )

    with open(destination_path, "wb") as out:
        out.write(new_elf)


# from ..a fuzzerstate, generates an ELF, may it be for spike resolution or for
# RTL simulation. Also integrates the final block.
# @param instrs an iterable (one per basic block) of iterables of
# CFInstrs or placeholders
# @param test_identifier typically the random seed, mem size, design name, max
# number of bbs
# @return the generated elf path
def gen_elf_from_bbs(
    testcase_generator: "TestCaseGenerator",
    is_spike_resolution: bool,
    prefixname: str,
    test_params: "TestParams",
    is_rtl: bool = False,
):
    """Generates an elf from from the list of instructions generated"""
    test_identifier = test_params.instance_to_str()
    is_rv64 = test_params.is_rv64
    memsize = test_params.memsize
    assert test_params.boot_addr == 0x80000000, "we must adapt elf loading then"

    fuzzerstate = testcase_generator.fuzzerstate

    # Create the bytecode for the ELF file
    addr_instrs = bytearray(memsize + MCM_RESET_HANDLER_LEN)
    stress_code = bytearray(0x1000)  # FIXME magic number

    ##
    # Fuzzing instructions
    ##

    for core in testcase_generator.corestates.values():
        if __debug__:
            assert len(core.basic_blocks) == len(core.bb_start_addrs)
        for bb_start_addr, bb_instrs in zip(core.bb_start_addrs, core.basic_blocks):
            if __debug__:
                assert addr_instrs[
                    bb_start_addr : bb_start_addr + ILEN * len(bb_instrs)
                ] == bytearray(ILEN * len(bb_instrs)), (
                    f"overwriting an address {hex(bb_start_addr)}"
                )
            for instr_id_in_bb, instr in enumerate(bb_instrs):
                curr_addr = bb_start_addr + ILEN * instr_id_in_bb  # NO_COMPRESSED
                curr_bytecode = instr.gen_bytecode_int(
                    is_spike_resolution=is_spike_resolution
                ).to_bytes(ILEN, "little")
                addr_instrs[curr_addr : curr_addr + ILEN] = curr_bytecode

    for core in testcase_generator.corestates.values():
        for bb_start_addr, handler_instr in zip(
            core.interrupt_handlers_start_addr, core.interrupt_handlers
        ):
            if __debug__:
                assert addr_instrs[
                    bb_start_addr : bb_start_addr + ILEN * len(handler_instr)
                ] == bytearray(ILEN * len(handler_instr)), (
                    f"overwriting an address {hex(bb_start_addr)}"
                )
                for instr_id_in_bb, instr in enumerate(handler_instr):
                    curr_addr = bb_start_addr + ILEN * instr_id_in_bb  # NO_COMPRESSED
                    curr_bytecode = instr.gen_bytecode_int(
                        is_spike_resolution=is_spike_resolution
                    ).to_bytes(ILEN, "little")
                    addr_instrs[curr_addr : curr_addr + ILEN] = curr_bytecode

    ##
    # Non-fuzzing instructions
    # WARNING: the final and initial block cannot be generated with the
    # spike_resolution flag, as we need the branch behaviour
    ##

    if __debug__:
        assert addr_instrs[
            fuzzerstate.init_bb_base_addr : fuzzerstate.init_bb_base_addr
            + ILEN * len(fuzzerstate.init_bb_instrs)
        ] == bytearray(ILEN * len(fuzzerstate.init_bb_instrs)), "overwriting an address"
        assert addr_instrs[
            fuzzerstate.mcm_state_rst_base_addr : fuzzerstate.mcm_state_rst_base_addr
            + ILEN * len(fuzzerstate.mcm_state_rst_instrs)
        ] == bytearray(ILEN * len(fuzzerstate.mcm_state_rst_instrs)), (
            "overwriting an address"
        )
        if fuzzerstate.final_bb_instrs:
            assert addr_instrs[
                fuzzerstate.get_final_bb_base_addr() : fuzzerstate.get_final_bb_base_addr()
                + ILEN * len(fuzzerstate.final_bb_instrs)
            ] == bytearray(ILEN * len(fuzzerstate.final_bb_instrs)), (
                "overwriting an address"
            )

    for instr_id_in_bb, instr in enumerate(fuzzerstate.init_bb_instrs):
        if instr is None:
            raise ValueError(f"instrobj is None for init at index {instr_id_in_bb}")
        curr_addr = fuzzerstate.init_bb_base_addr + ILEN * instr_id_in_bb
        curr_bytecode = instr.gen_bytecode_int(False).to_bytes(ILEN, "little")
        addr_instrs[curr_addr : curr_addr + ILEN] = curr_bytecode

    for instr_id_in_bb, instr in enumerate(fuzzerstate.mcm_state_rst_instrs):
        if instr is None:
            raise ValueError(f"instrobj is None for init at index {instr_id_in_bb}")
        curr_addr = fuzzerstate.mcm_state_rst_base_addr + ILEN * instr_id_in_bb
        curr_bytecode = instr.gen_bytecode_int(False).to_bytes(ILEN, "little")
        addr_instrs[curr_addr : curr_addr + ILEN] = curr_bytecode

    for reg_data_id, reg_data_doubleword in enumerate(
        fuzzerstate.initial_reg_data_content
    ):
        curr_addr = fuzzerstate.initial_reg_data_addr + DWORD_SIZE * reg_data_id
        curr_bytecode = reg_data_doubleword.to_bytes(DWORD_SIZE, "little")
        assert addr_instrs[curr_addr : curr_addr + DWORD_SIZE] == bytearray(DWORD_SIZE)
        addr_instrs[curr_addr : curr_addr + DWORD_SIZE] = curr_bytecode

    for instr_id_in_bb, instr in enumerate(fuzzerstate.final_bb_instrs):
        curr_bytecode = instr.gen_bytecode_int(False).to_bytes(4, "little")
        curr_addr = fuzzerstate.get_final_bb_base_addr() + ILEN * instr_id_in_bb
        addr_instrs[curr_addr : curr_addr + ILEN] = curr_bytecode

    # generate stress code
    for instr_id_in_bb, instr in enumerate(fuzzerstate.stress_bb):
        curr_bytecode = instr.gen_bytecode_int(False).to_bytes(4, "little")
        curr_addr = ILEN * instr_id_in_bb
        stress_code[curr_addr : curr_addr + ILEN] = curr_bytecode

    elfpath = os.path.join(
        runparams.PATH_TO_TMP, "elfs", f"{prefixname}{test_identifier}.elf"
    )

    # Generate the ELF object
    gen_elf(addr_instrs, stress_code, elfpath, is_rv64, test_params.design_name, is_rtl)
    return elfpath
