#![allow(non_camel_case_types)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ISAInstrClass {
    REGFSM = 1,
    FPUFSM = 2,
    ALU = 3,
    ALU64 = 4,
    MULDIV = 5,
    MULDIV64 = 6,
    AMO = 7,
    AMO64 = 8,
    JAL = 9,
    JALR = 10,
    BRANCH = 11,
    MEM = 12,
    MEM64 = 13,
    MEMFPU = 14,
    FPU = 15,
    FPU64 = 16,
    MEMFPUD = 17,
    FPUD = 18,
    FPUD64 = 19,
    EXCEPTION = 20,
    RANDOM_CSR = 21,
    DESCEND_PRV = 22,
    FENCE = 23,
    WFI_TRAP = 24,
    WFI_NOTRAP = 25,
    SEND_IPI = 26,
    SEND_LOCAL_INTERRUPT = 27,
    CLEAR_INTERRUPT = 28,
    EPCFSM = 29,
    TVECFSM = 30,
    MACHINE_CSR = 31,
    FREE_POLLUTED = 32,
    CREATE_ADDR_DEP = 33,
    CLEAR_MDT = 34,
    RESET_MCM = 35,
    WRITE_INSTR = 36,
    WAIT_FOR_INSTR = 37,
}

pub const BASE_DISTRIBUTION: &[(ISAInstrClass, f64)] = &[
    (ISAInstrClass::ALU, 0.1),
    (ISAInstrClass::ALU64, 0.1),
    (ISAInstrClass::MULDIV, 0.1),
    (ISAInstrClass::MULDIV64, 0.1),
    (ISAInstrClass::JAL, 0.01),
    (ISAInstrClass::JALR, 0.01),
    (ISAInstrClass::BRANCH, 0.4),
    (ISAInstrClass::MEM, 0.5),
    (ISAInstrClass::MEM64, 0.5),
    (ISAInstrClass::AMO, 0.0),
    (ISAInstrClass::AMO64, 0.0),
    (ISAInstrClass::FENCE, 1e-06),
    (ISAInstrClass::MEMFPU, 0.0),
    (ISAInstrClass::MEMFPUD, 0.0),
    (ISAInstrClass::FPUFSM, 0.0),
    (ISAInstrClass::FPU, 0.0),
    (ISAInstrClass::FPU64, 0.0),
    (ISAInstrClass::FPUD, 0.0),
    (ISAInstrClass::FPUD64, 0.0),
    (ISAInstrClass::REGFSM, 0.1),
    (ISAInstrClass::TVECFSM, 0.1),
    (ISAInstrClass::EPCFSM, 0.1),
    (ISAInstrClass::FREE_POLLUTED, 5.0),
    (ISAInstrClass::CREATE_ADDR_DEP, 2.0),
    (ISAInstrClass::MACHINE_CSR, 0.1),
    (ISAInstrClass::EXCEPTION, 0.1),
    (ISAInstrClass::RANDOM_CSR, 0.0),
    (ISAInstrClass::DESCEND_PRV, 0.1),
    (ISAInstrClass::WFI_TRAP, 0.7),
    (ISAInstrClass::WFI_NOTRAP, 0.4),
    (ISAInstrClass::SEND_IPI, 5.0),
    (ISAInstrClass::SEND_LOCAL_INTERRUPT, 0.0),
    (ISAInstrClass::CLEAR_INTERRUPT, 0.4),
    (ISAInstrClass::WRITE_INSTR, 0.0),
    (ISAInstrClass::WAIT_FOR_INSTR, 0.0),
    (ISAInstrClass::CLEAR_MDT, 0.0),
    (ISAInstrClass::RESET_MCM, 0.0),
];
